kind = "web"
previewPath = "/"
title = "Devtraco Plus"
version = "1.0.0"
id = "artifacts/devtraco-plus"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25907

[services.development]
run = "pnpm --filter @workspace/devtraco-plus run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/devtraco-plus", "run", "build" ]
publicDir = "artifacts/devtraco-plus/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25907"
BASE_PATH = "/"
