uploads = []
outputs = []

[[generated]]
id = "a1IsqUDVHJL9iQtQ7gWYl"
uri = "file://attached_assets/generated_images/generated_image_0.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_j4Ah4I1oGvFSMtpVNsnJ"
uri = "file://attached_assets/generated_images/generated_image_1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "7RKAnjL9wKO5FgHloVjFK"
uri = "file://attached_assets/generated_images/generated_image_2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2yqoeq2wyyNNFLtgBr__2"
uri = "file://attached_assets/generated_images/generated_image_3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QKQv6y9CyscQTl2DVUOAc"
uri = "file://attached_assets/generated_images/generated_image.png"
type = "image"
title = "generated_image"
